module.exports.cars = [
  {
    brand: 'Volvo',
    model: 'XC90',
    year: 2022,
    color: 'Blue',
    engine_type: 'Hybrid',
    bodywork_type: 'SUV',
    gear_type: 'Automatic',
    new: true,
    logo: null,
    typeId: '66c72944e16558503bb31c28',
  },
  {
    brand: 'Porsche',
    model: '911',
    year: 2023,
    color: 'Red',
    engine_type: 'Gasoline',
    bodywork_type: 'Coupe',
    gear_type: 'Manual',
    new: true,
    logo: null,
    typeId: '66c72944e16558503bb31c29',
  },
  {
    brand: 'Tesla',
    model: 'Model S',
    year: 2023,
    color: 'Red',
    engine_type: 'Electric',
    bodywork_type: 'Sedan',
    gear_type: 'Automatic',
    new: true,
    logo: null,
    typeId: '66c72944e16558503bb31c26',
  },
  {
    brand: 'Audi',
    model: 'Q7',
    year: 2020,
    color: 'White',
    engine_type: 'Diesel',
    bodywork_type: 'SUV',
    gear_type: 'Automatic',
    new: false,
    logo: null,
    typeId: '66c72944e16558503bb31c27',
  },
  {
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2021,
    color: 'Blue',
    engine_type: 'Gasoline',
    bodywork_type: 'Sedan',
    gear_type: 'Automatic',
    new: false,
    logo: null,
    typeId: '66c72944e16558503bb31c26',
  },
  {
    brand: 'Ford',
    model: 'Mustang',
    year: 2022,
    color: 'Yellow',
    engine_type: 'Gasoline',
    bodywork_type: 'Coupe',
    gear_type: 'Manual',
    new: true,
    logo: null,
    typeId: '66c72944e16558503bb31c29',
  },
  {
    brand: 'Honda',
    model: 'Civic',
    year: 2023,
    color: 'Gray',
    engine_type: 'Hybrid',
    bodywork_type: 'Sedan',
    gear_type: 'Automatic',
    new: true,
    logo: null,
    typeId: '66c72944e16558503bb31c26',
  },
  {
    brand: 'Chevrolet',
    model: 'Tahoe',
    year: 2019,
    color: 'Black',
    engine_type: 'Gasoline',
    bodywork_type: 'SUV',
    gear_type: 'Automatic',
    new: false,
    logo: null,
    typeId: '66c72944e16558503bb31c27',
  },
  {
    brand: 'Lexus',
    model: 'RX 350',
    year: 2021,
    color: 'Silver',
    engine_type: 'Gasoline',
    bodywork_type: 'SUV',
    gear_type: 'Automatic',
    new: false,
    logo: null,
    typeId: '66c72944e16558503bb31c28',
  },
  {
    brand: 'Nissan',
    model: 'Altima',
    year: 2022,
    color: 'White',
    engine_type: 'Gasoline',
    bodywork_type: 'Sedan',
    gear_type: 'Automatic',
    new: true,
    logo: null,
    typeId: '66c72944e16558503bb31c26',
  },
];

module.exports.types = [
  {
    type: 'Truck',
  },
  {
    type: 'Passenger car',
  },
  {
    type: 'Jeep',
  },
  {
    type: 'Crossover',
  },
  {
    type: 'Sport',
  },
  {
    type: 'Military',
  },
  {
    type: 'Concept',
  },
];
